#pragma once

#include "RoutePipelineTypes.h"

namespace RouteAlgo {

class RoutePipelineDebug;

// ---------------------------------------------------------------------------
// Stage 2 — Sweep
// ---------------------------------------------------------------------------
// Generates parallel "stripes" by intersecting infinite lines with the
// working area. Lines start at the anchor d-coordinate and step outward in
// both directions (user-preferred side first).
//
// May make several passes against the residual area to fill in pockets that
// the first sweep direction couldn't reach with a single set of lines.
//
// Inputs:
//   * insetRegion, insetGeo, nearestPt, lineDir, normal, tuning  (Stage 1)
//   * stepMeters, rightSide, routeDebug                          (input)
// Outputs:
//   * rawStripes        — every segment generated by all passes
//   * sweepRowCount     — total number of distinct rows produced
//   * passesExecuted    — how many passes actually contributed
//   * residualRegion    — uncovered remainder after the sweep
bool runStageSweep(const RoutePipelineInput& input, RoutePipelineState& state,
                   RoutePipelineDebug& debug);

}  // namespace RouteAlgo
